# Arquivo: psono-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: psono-secret
  # (Recomendo criar um namespace 'psono' para organizar tudo)
  namespace: psono 
type: Opaque
data:
  # --- Senha do Banco de Dados ---
  # (Pegue a senha do seu Azure PostgreSQL (Passo 1) e converta para Base64)
  POSTGRES_PASSWORD: Uzg4RCp5RkMqMVJFIVAkR3B5Xm0=

  # --- Chaves Secretas do Psono ---
  # (Pegue estes valores do seu settings.yaml no WSL e converta para Base64)
  SECRET_KEY: QVR3SnFhOGhqUFFSbWVIclZQWjlRakNjQVg0ZDJ3QUdlWHJQREF6YmZUTkhMRG5KZkxueUw3SngxejF3THl6dg==
  PRIVATE_KEY: NmRkYzY2YmFmMmEzYTk0MWQxMDMzNzA2YjU2ZDg0MzVlODBkMjhhYzJhODM4NzBiZGM4MGExNjk4NTk1NmIxYw==
  PUBLIC_KEY: MTYzY2FjYjFiMjk5YWU5Mzc5Zjc4ODlhNDdhOTM5YjAzODFkYzI5MTBlZTU2Y2NiZTQ5YmE0NzVlMTdlYmExZA==
  ACTIVATION_LINK_SECRET: MzRHdVFzemd1N3hpT0NTSUNOYVhJU3g2dHcydjlqSDgwUkpNTHplUUZTMjJOUTNpUFZhZlJtbU13WGxzM2hKNA==
  DB_SECRET: SHozNkhFbHF1aWlQQ0xWWjdySGJ4YUpUWkZBQkVJM0lwOWgyZ20wVTE0R3dwd1h4dWsyeWVaR1N2UXdvNEZ3ag==
  EMAIL_SECRET_SALT: JDJiJDEyJENvUnZaVGpPMGJjZDI2NDNzcDdBeC4=